version: "3"

networks:
  chatbot-network:
    driver: bridge

services:
  chatboot:
    image: chatbot
    tty: true # docker run -t
    restart: unless-stopped
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./:/code
    env_file:   # Adicione esta linha
      - .env    # Especifique o caminho para o seu arquivo .env
    networks:
      chatbot-network:
  nginx:
    image: nginx:1.21
    tty: true
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/api.conf:/etc/nginx/conf.d/default.conf
      - ./:/code
    networks:
      chatbot-network: